### ISSUE TITLE
[v1.1.1] Tests protractor en échec

### ISSUE THREAD

**Issue by julienmourgues** [angular-starter-kit/starter-kit#66]
Bonjour,

J'ai constaté que les tests e2e étaient en échec sur la version 1.1.1.
En mettant à jour la version de gulp-protractor, le problème est résolu.

Voici la correction dans le fichier package.json : "gulp-protractor": "^4.1.0".
A noter que j'utilise la version 59.0.3071.115 de Chrome.

Cordialement,
Julien Mourgues

**Comment by sinedied** [comment]
Thanks, the fix is currently waiting in a PR to be merge on the generator, so this will be fixed soon ;)

**Comment by sinedied** [comment]
Resolved with latest generator update.
